### ISSUE TITLE
Milestone v2.1

### ISSUE THREAD

**Issue by mudar** [mudar/MontrealJustInCase#28]
- [ ] #26 Update data from API
- [ ] #17 Add Air-conditionned facilities
- [ ] #15 Add filter to Water supplies

**Comment by mudar** [comment]
unused ticket, duplicate of milestone view
